version: "3.8"
services:
  api:
    build:
      args:
        user: api-user
        uid: 1000
      context: .
      dockerfile: Dockerfile
    container_name: lumen-api
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: api
      SERVICE_TAGS: dev
    working_dir: /var/www
    networks:
      - backend

  #Nginx Service
  apiserver:
    image: nginx:alpine
    container_name: api-server
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "9001:80"
      #- "443:443" enable on prod to open ssl ports
    networks:
      - backend


   #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: lumen
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - backend
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf

networks:
  backend:

#Volumes
volumes:
  dbdata:
    driver: local
