name: Lumem

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:

    runs-on: ubuntu-latest
    services:
      mysql:
          image: mysql:5.7
          env:
            MYSQL_USER: root
            MYSQL_DATABASE: asorifieprotesting
            MYSQL_ROOT_PASSWORD: my-secret-pw
          ports:
            - 3306
          options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v2
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.ci', '.env');"

    - name: Install Dependencies
      run: composer install -n --prefer-dist


    - name: Execute tests (Unit and Feature tests) via PEST PHP
      env:
        DB_PORT: ${{ job.services.mysql.ports[3306] }}
        
      run: composer test